# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

executors:
  my-custom-executor:
    docker:
      - image: cimg/node:lts
      
jobs:
  build-and-test:
    executor: my-custom-executor
    steps:
      - checkout
      - node/install-packages
      - run: |
          name: Run tests
          command: npm test

workflows:
  my-custom-workflow:
    jobs:
      - build-and-test